URL: http://10.168.92.105:7721/api

PacketOrder: http://10.168.92.105:7721/api/Forecast/PacketOrder

LabelResult: http://10.168.92.105:7721/api/Receive/LabelResult

omsUrl: http://10.168.95.33:6569
User: test
passwd: 123456
headers : {'Content-Type': 'application/json' }


#配置数据库
dbotsname: ots_db
dbotshost: IT-100
dbotsport: 3308
dbotsuser: mysql
dbotspassword: a135246A
dbotscharset: utf8

